name: CI
on:
  push:
  workflow_dispatch:

concurrency:
  group: QA-cluster
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Simulate doing something
        run: echo ${{ github.ref }} 
      - name: Simulate doing something
        run: sleep 1m
